version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev 
      POSTGRES_DB: testing 
  database-explorer:
    image: 'dpage/pgadmin4:latest'
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: 'shahan.neda@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'dev'
      PGADMIN_DEFAULT_PORT: '5433'
